# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoundCastSampleObjectiveC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   pod 'SoundCastIosSdk', '~> 1.5.0.8'
   platform :ios, '9'
end
